disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - trailing_whitespace
  - cyclomatic_complexity
  - function_parameter_count

opt_in_rules:
  - empty_count

excluded:
  - Carthage
  - Pods
  - Borderify.xcodeproj
